#!/bin/sh

set -e

. /usr/share/debconf/confmodule

add_group_if_missing() {
    if ! getent group rmsgw >/dev/null; then
        addgroup --system --allow-bad-names rmsgw || true
    fi
}

add_user_if_missing() {
    if ! id -u rmsgw > /dev/null 2>&1; then
        adduser --system --no-create-home \
          --disabled-password \
          --allow-bad-names rmsgw \
          --ingroup rmsgw
    fi
}

fix_permissions() {
    chown -R rmsgw:rmsgw /etc/rmsgw/stat
}

add_group_if_missing
add_user_if_missing
fix_permissions

db_stop
